CREATE TABLE PlacementDiary (
  id   CHAR(5) PRIMARY KEY,
  date  DATE     NOT NULL,
  work TEXT NOT NULL,
  exp TEXT NOT NULL,
  comp TEXT NOT NULL
);

INSERT INTO PlacementDiary (id, date, work, exp, comp)
VALUES
  ('1', 
   '2021-07-13', 
   'First day of work, Im becoming familiar with the office and colleagues. Got issued a work laptop & given access to company systems. Started company training.', 
   'Use of Linux in a work environment. Learned to set up Linux dev env. Brief introduction to GDPR. Completed course: Cyber Essentials', 
   'B3,E1,E2,E5'),
  ('2', 
  '2023-07-14', 
  'Completed my first few customer support cases.', 
  'First cases enabled me to personalise my dev env a little and get familiarise with new tools like Banjax Ultracloot. First interactions with support and learning to better communicate requirements.', 
  'A1,A2,B3'),
  ('3', 
   '2022-07-14', 
   'Completed my first few customer support cases.', 
   'First cases enabled me to personalise my dev env a little and get familiarise with new tools like Banjax Ultracloot. First interactions with support and learning to better communicate requirements.', 
   'A1,A2,B3');

CREATE TABLE Competence (
  id   CHAR(5) PRIMARY KEY,
  standards TEXT NOT NULL,
  examples TEXT
);

INSERT INTO Competence (id, standards, examples)
VALUES
  ('A', 
   'Use a combination of general and specialist engineering knowledge and understanding to apply existing and emerging technology', 
   ''),
  ('A1', 
   'Maintain and extend a sound theoretical approach to the application of technology in engineering practice.', 
   'Engage in formal learning. Learn new engineering theories and techniques in the workplace, at seminars, etc. Broaden your knowledge of engineering codes, standards and specifications'),
  ('A2', 
   'Use a sound evidence-based approach to problem-solving and contribute to continuous improvement.', 
   'Manage/contribute to market research, and product and process research and development. Involvement with cross-disciplinary working. Conduct statistically sound appraisal of data. Use evidence from best practice to improve effectiveness. Apply root cause analysis.'),
  ('B', 
   'Apply appropriate theoretical and practical methods to design, develop, manufacture, construct, commission, operate, maintain, decommission and re-cycle engineering processes, systems, services and products', 
   ''),
  ('B1', 
   'Identify, review and select techniques, procedures and methods to undertake engineering tasks.', 
   'Contribute to the marketing of and tendering for new engineering products, processes and systems. Contribute to the specification and procurement of new engineering products, processes and systems. Develop decommissioning processes. Set targets, and draft programmes and action plans. Schedule activities.'),
  ('B2', 
   'Contribute to the design and development of engineering solutions.', 
   'Contribute to theoretical and applied research. Manage/contribute to value engineering and whole life costing. Work in design teams. Draft specifications. Find and evaluate information from a variety of sources, including online. Develop and test options. Identify resources and costs of options. Produce detailed designs. Be aware of IP constraints and opportunities.'),
  ('B3', 
   'Implement design solutions and contribute to their evaluation.', 
   'Follow the design process through into product manufacture. Operate and maintain processes, systems etc. Contribute to reports on the evaluation of the effectiveness of the designs, including risk, safety and life cycle considerations. Contribute to product improvement. Interpret and analyse performance. Contribute to determining critical success factors.'),
  ('C', 
   'Provide technical and commercial management.', 
   ''),
  ('C1', 
   'Plan for effective project implementation', 
   'Manage/contribute to project planning activities. Produce and implement procurement plans. Contribute to project risk assessments. Collaborate with key stakeholders. Plan programmes and delivery of tasks. Identify resources and costs. Prepare and agree contracts/work orders.'),
  ('C2', 
   'Manage tasks, people and resources to plan and budget.', 
   'Manage/contribute to project operations. Manage the balance between quality, cost and time. Manage contingency processes. Contribute to the management of project funding, payments and recovery. Satisfy legal and statutory obligations. Manage tasks within identified financial, commercial and regulatory constraints.'),
  ('C3', 
   'Manage teams and develop staff to meet changing technical and managerial needs.', 
   'Carry out/contribute to staff appraisals. Plan/contribute to the training and development of staff. Gather evidence from colleagues of the management, assessment and feedback that you have provided. Carry out/contribute to disciplinary procedures.'),
  ('C4', 
   'Manage continuous quality improvement.', 
   'Promote quality. Manage/contribute to best practice methods of continuous improvement, eg ISO 9000, EFQM, balanced scorecard. Carry out/contribute to quality audits. Monitor, maintain and improve delivery. Identify, implement and evaluate changes to meet quality objectives.'),
  ('D', 
   'Demonstrate effective interpersonal skills.', 
   ''),
  ('D1', 
   'Communicate in English with others at all levels.', 
   'Reports, letters, emails, drawings, specifications and working papers (eg meeting minutes, planning documents, correspondence) in a variety of formats. Engaging or interacting with professional networks'),
  ('D2', 
   'Present and discuss proposals.', 
   'Presentations, records of discussions and their outcomes.'),
  ('D3', 
   'Demonstrate personal and social skills.', 
   'Records of meetings. Evidence from colleagues of your personal and social skills. Contribute to productive working relationships. Apply diversity and anti-discrimination legislation.'),
  ('E', 
   'Demonstrate a personal commitment to professional standards, recognizing obligations to society, the profession and the environment.', 
   ''),
  ('E1', 
   'Comply with relevant codes of conduct.', 
   'Contribute to the affairs of your institution. Work with a variety of conditions of contract.'),
  ('E2', 
   'Manage and apply safe systems of work.', 
   'Undertake formal health and safety training. Work with health and safety legislation and best practice. In the UK, examples include HASAW 1974, CDM regulations, OHSAS 18001:2007 and company safety policies. Carry out safety audits. Identify and minimize hazards. Assess and control risks. Deliver health and safety briefings and inductions.'),
  ('E3', 
   'Undertake engineering activities in a way that contributes to sustainable development.', 
   'Carry out/contribute to environmental impact assessments. Carry out/contribute to environmental risk assessments. Manage best practice environmental management systems, eg ISO 14000. Manage best practice risk management systems eg ISO 31000. Work within environmental legislation. Adopt sustainable practices. Contribute to social, economic and environmental outcomes.'),
  ('E4', 
   'Carry out and record CPD necessary to maintain and enhance competence in own area of practice', 
   'Keep up to date with national and international engineering issues. Maintain CPD plans and records. Involvement with the affairs of your institution. Evidence of your development through on-the-job learning, private study, in-house courses, external courses and conferences.'),
  ('E5', 
   'Exercise responsibilities in an ethical manner.', 
   'Give an example of where you have applied ethical principles as described in the Statement of Ethical Principles on page 33. Give an example of where you have applied/upheld ethical principles as defined by your organization or company, which may be in its company or brand values.');


